### ISSUE TITLE
Disabling login causes websocket connections to be unavailable

### ISSUE THREAD

**Issue by Aetheron** [willg101/vortex#5]
**Describe the bug**
When disabling the login feature by deleting `login` from `modules_enabled`, Vortex infinitely displays toasts saying "no websocket connection is available"

**To Reproduce**
1. Clone the repo
2. `rm modules_enabled/login`
3. `./spinup`
4. Load vortex in a browser

**Expected behavior**
Vortex should load into the main interface immediately with no error messages

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Browser: Chrome

**Additional context**
Vortex version: Beta 1.3.0

**Comment by willg101** [comment]
Addressed in 86ee702c95118342600b5ca12a149b50c11d1e5f
